import { StyleSheet } from 'react-native';
import { GREEN_ACCENT, SCREEN_WIDTH, SCREEN_HEIGHT } from './Chatconstants';

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 0.5, borderBottomColor: '#ccc' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  headerName: { fontSize: 18, fontFamily: 'Nunito-Bold', maxWidth: 150 },
  headerSubtitle: { fontSize: 12, color: '#888', fontFamily: 'Nunito-Regular' },
  headerRight: { flexDirection: 'row', alignItems: 'center' },
  headerIconBtn: { padding: 6 },
  avatarCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#00A3FF', justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, },
  avatarText: { color: '#FFEE00', fontSize: 20, fontWeight: 'bold', fontStyle: 'italic' },
  toolHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 12, justifyContent: 'space-between' },
  toolIcon: { alignItems: 'center', paddingHorizontal: 4 },
  toolText: { fontSize: 12.5, marginTop: 2, fontFamily: 'Nunito-Regular' },
  messagesList: { paddingVertical: 20, gap: 3 },
  myMessageRow: { flexDirection: 'row', alignItems: 'flex-end', width: '100%', paddingHorizontal: 10, paddingVertical: 4 },
  otherMessageRow: { flexDirection: 'row', alignItems: 'flex-end', width: '100%', paddingHorizontal: 10, paddingVertical: 4 },
  bubbleAvatarCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#00A3FF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#FFEE00' },
  bubbleAvatarText: { color: '#FFEE00', fontSize: 15, fontWeight: 'bold' },
  myMessageBubble: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 15, maxWidth: '100%', flexShrink: 1, elevation: 1 },
  otherMessageBubble: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 15, maxWidth: '100%', flexShrink: 1, elevation: 1 },
  messageText: { fontSize: 16, fontFamily: 'Nunito-Regular', lineHeight: 20 },
  timeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', marginTop: 4, alignSelf: 'flex-end' },
  messageTime: { fontSize: 13, fontFamily: 'Nunito-Regular' },
  inputContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  textInputWrapper: { flex: 1, flexDirection: 'row', alignItems: 'center', borderRadius: 25, paddingHorizontal: 8, minHeight: 48, maxHeight: 100 },
  textInput: { flex: 1, fontSize: 16, fontFamily: 'Nunito-Regular', paddingHorizontal: 10, paddingVertical: 8 },
  actionButton: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center' },
  infoOverlay: {position: 'absolute',top: 100,left: 20,right: 20,padding: 16,borderRadius: 12,borderWidth: 1,shadowColor: '#000',shadowOffset: { width: 0, height: 2 },shadowOpacity: 0.2,shadowRadius: 4,elevation: 5,zIndex: 100,},
  infoTitle: {fontSize: 16,fontFamily: 'Nunito-Bold',marginBottom: 12,},
  infoLine: {flexDirection: 'row',alignItems: 'center',marginVertical: 6,},
  infoLabel: {fontWeight: 'bold',marginLeft: 6,},
  infoCloseBtn: {marginTop: 14,alignSelf: 'flex-end',},
  infoCloseText: {color: GREEN_ACCENT,fontWeight: 'bold',},
  dropdownMenu: {position: 'absolute',top: 90,right: 16,borderRadius: 12,borderWidth: 0.5,shadowColor: '#000',shadowOffset: { width: 0, height: 2 },shadowOpacity: 0.15,shadowRadius: 4,elevation: 4,zIndex: 99,minWidth: 200,paddingVertical: 6,},
  dropdownItem: {paddingVertical: 12,paddingHorizontal: 16,},
  dropdownItemText: {fontSize: 14,fontFamily: 'Nunito-Regular',},
  subDropdownMenu: {borderRadius: 8,borderWidth: 0.5,marginTop: 4,marginHorizontal: 8,paddingVertical: 4,},
  attachmentTray: {position: 'absolute',bottom: 120,right: 20,left: 20,borderRadius: 15,borderWidth: 0.5,shadowColor: '#000',shadowOffset: { width: 0, height: -2 },shadowOpacity: 0.15,shadowRadius: 4,elevation: 4,zIndex: 98,padding: 16,flexDirection: 'row',justifyContent: 'space-around',},
  attachmentItem: {alignItems: 'center',width: 65,},
  attachmentText: {fontSize: 12,marginTop: 4,fontFamily: 'Nunito-Regular',textAlign: 'center',},
  lockedRecordContainer: {position: 'absolute',left: 12,right: 12,padding: 14,borderRadius: 24,borderWidth: 1,gap: 12,zIndex: 50,elevation: 8,shadowColor: '#000',shadowOffset: { width: 0, height: 4 },shadowOpacity: 0.2,shadowRadius: 6,},
  recordTopRow: {flexDirection: 'row',alignItems: 'center',justifyContent: 'space-between',paddingHorizontal: 8,},
  recordSeconds: {fontSize: 16,fontFamily: 'Nunito-Bold',minWidth: 50,},
  waveformContainer: {flexDirection: 'row',alignItems: 'center',gap: 3,flex: 1,justifyContent: 'center',paddingHorizontal: 12,height: 36,},
  waveBar: {width: 3,height: 32,borderRadius: 1.5,},
  recordActionRow: {flexDirection: 'row',alignItems: 'center',justifyContent: 'space-between',gap: 10,paddingHorizontal: 4,},
  recordDiscardButton: {width: 44,height: 44,borderRadius: 22,justifyContent: 'center',alignItems: 'center',},
  recordSendButton: {width: 44,height: 44,borderRadius: 22,justifyContent: 'center',alignItems: 'center',elevation: 2,},
  recordPausePill: {flex: 1,flexDirection: 'row',alignItems: 'center',justifyContent: 'center',gap: 8,height: 48,borderRadius: 24,},
  recordPauseLabel: {fontSize: 15,fontFamily: 'Nunito-Bold',},
  recordHintBar: {flex: 1,flexDirection: 'row',alignItems: 'center',justifyContent: 'space-between',borderRadius: 25,paddingHorizontal: 16,minHeight: 48,},
  cancelHintRow: {flexDirection: 'row',alignItems: 'center',gap: 4,},
  cancelHintText: {fontSize: 14,fontFamily: 'Nunito-Regular',},
  actionButtonRecording: {width: 56,height: 56,borderRadius: 28,marginRight: -4,marginBottom: -4,elevation: 3,},
  lockIndicator: {position: 'absolute',bottom: 64,right: 4,width: 36,paddingVertical: 8,borderRadius: 18,alignItems: 'center',elevation: 3,shadowColor: '#000',shadowOffset: { width: 0, height: 1 },shadowOpacity: 0.15,shadowRadius: 2,},
  waContainer: {flexDirection: 'row',alignItems: 'center',paddingVertical: 6,paddingHorizontal: 6,borderRadius: 8,width: 280,},
  waPlayBtn: {width: 30,height: 30,borderRadius: 15,justifyContent: 'center',alignItems: 'center',marginRight: 6,},
  waWaveform: {flex: 1,flexDirection: 'row',alignItems: 'center',height: 28,gap: 2,position: 'relative',},
  waBar: {width: 3,borderRadius: 1.5,},
  waDuration: {fontSize: 11,fontFamily: 'Nunito-Regular',minWidth: 28,textAlign: 'right',marginLeft: 6,},
  waDot: {position: 'absolute',top: '50%',marginTop: -4,zIndex: 10,},
  toast: {position: 'absolute',bottom: 112,left: 20,right: 20,backgroundColor: '#323232',flexDirection: 'row',alignItems: 'center',justifyContent: 'center',gap: 8,paddingVertical: 12,paddingHorizontal: 20,borderRadius: 12,elevation: 6,shadowColor: '#000',shadowOffset: { width: 0, height: 3 },shadowOpacity: 0.3,shadowRadius: 5,zIndex: 999,},
  toastText: {color: '#FFF',fontSize: 15,fontFamily: 'Nunito-Bold',},
  deleteConfirm: {position: 'absolute',left: 16,right: 16,padding: 16,borderRadius: 16,borderWidth: 1,gap: 14,shadowColor: '#000',shadowOffset: { width: 0, height: 4 },shadowOpacity: 0.2,shadowRadius: 6,elevation: 8,zIndex: 100,},
  deleteConfirmText: {fontSize: 16,fontFamily: 'Nunito-Bold',textAlign: 'center',},
  deleteConfirmActions: {flexDirection: 'row',gap: 12,},
  deleteConfirmBtn: {flex: 1,flexDirection: 'row',alignItems: 'center',justifyContent: 'center',gap: 6,paddingVertical: 12,borderRadius: 12,},
  deleteConfirmBtnText: {fontSize: 15,fontFamily: 'Nunito-Bold',},

  // --- Miniaturas dentro de la burbuja del chat ---
  mediaThumb: { width: 250, height: 250, borderRadius: 12, backgroundColor: '#0002' },
  mediaPlayOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center' },
  fileCard: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 4, maxWidth: 220 },
  fileName: { fontSize: 14, fontFamily: 'Nunito-Bold', flexShrink: 1 },

  // --- Visor de media a pantalla completa ---
  mediaViewerContainer: { flex: 1, backgroundColor: '#121212' },
  mediaViewerHeader: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingBottom: 10 },
  mediaViewerCloseBtn: { padding: 6 },
  mediaViewerCounter: { color: '#FFF', fontSize: 14, fontFamily: 'Nunito-Bold' },
  mediaViewerPage: { width: SCREEN_WIDTH, height: SCREEN_HEIGHT, justifyContent: 'center', alignItems: 'center' },
  mediaViewerFileCard: { alignItems: 'center', gap: 14, paddingHorizontal: 30 },
  mediaViewerFileName: { color: '#FFF', fontSize: 16, fontFamily: 'Nunito-Bold', textAlign: 'center' },
  mediaViewerFileBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: GREEN_ACCENT, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 24, marginTop: 10 },
  mediaViewerFileBtnText: { color: '#FFF', fontSize: 14, fontFamily: 'Nunito-Bold' },

  mediaTimeBadge: {position: 'absolute',bottom: 6,right: 6,flexDirection: 'row',alignItems: 'center',backgroundColor: 'rgba(0,0,0,0.45)',borderRadius: 10,paddingHorizontal: 6,paddingVertical: 2,},
  mediaTimeBadgeText: {color: '#FFF',fontSize: 11,fontFamily: 'Nunito-Regular',},
});

export default styles;