using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Google.Cloud.Firestore;

namespace BackendDotnet.Services
{
    public class SeedService
    {
        private readonly FirestoreDb _firestoreDb;

        public SeedService(FirestoreDb firestoreDb)
        {
            _firestoreDb = firestoreDb;
        }

        public async Task SeedAsync()
        {
            AggregateQuerySnapshot countSnap = await _firestoreDb.Collection("posts").Count().GetSnapshotAsync();
            if ((int)countSnap.Count > 0) return;

            Console.WriteLine("🌱 Sembrando datos de prueba...");

            var seedPosts = new List<Dictionary<string, object>>
            {
                new() { { "titulo", "Soporte auriculares PLA" }, { "descripcion", "Soporte premium para auriculares impreso en PLA color negro. Diseño ergonómico con base antideslizante." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post01/400/300" } }, { "precio", 5000.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 1200 }, { "estado", "disponible" }, { "totalComentarios", 5 }, { "totalLikes", 12 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-30)) } },
                new() { { "titulo", "Figura de dragón articulada" }, { "descripcion", "Increíble figura coleccionable articulada impresa en resina de alta definición. 20 cm de alto, múltiples puntos de articulación." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post02/400/300", "https://picsum.photos/seed/post02b/400/300", "https://picsum.photos/seed/post02c/400/300" } }, { "precio", 12000.0 }, { "webLink", null }, { "autor", "seed_user_2" }, { "vistas", 890 }, { "estado", "disponible" }, { "totalComentarios", 3 }, { "totalLikes", 8 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-28)) } },
                new() { { "titulo", "Maqueta Estadio Boca Juniors" }, { "descripcion", "Maqueta detallada del estadio Alberto J. Armando (La Bombonera). Escala 1:500, incluye techo y plateas." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post03/400/300", "https://picsum.photos/seed/post03b/400/300" } }, { "precio", 15000.0 }, { "webLink", "https://example.com/maqueta-boca" }, { "autor", "seed_user_3" }, { "vistas", 4500 }, { "estado", "disponible" }, { "totalComentarios", 15 }, { "totalLikes", 142 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-25)) } },
                new() { { "titulo", "Maceta geométrica minimalista" }, { "descripcion", "Maceta de diseño nórdico para plantas de interior. Diámetro 12cm, incluye vaso interior para drenaje." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post04/400/300" } }, { "precio", 1500.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 310 }, { "estado", "disponible" }, { "totalComentarios", 1 }, { "totalLikes", 4 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-22)) } },
                new() { { "titulo", "Llavero logo Batman" }, { "descripcion", "Llavero clásico impreso en filamento PLA fluorescente. Tamaño 5cm, incluye argolla metálica." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post05/400/300" } }, { "precio", 500.0 }, { "webLink", null }, { "autor", "seed_user_4" }, { "vistas", 2100 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 25 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-20)) } },
                new() { { "titulo", "Organizador de escritorio modular" }, { "descripcion", "Set modular de organizador con portalápices, tarjetero y bandeja para clips. Piezas intercambiables." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post06/400/300", "https://picsum.photos/seed/post06b/400/300", "https://picsum.photos/seed/post06c/400/300", "https://picsum.photos/seed/post06d/400/300" } }, { "precio", 3500.0 }, { "webLink", null }, { "autor", "seed_user_2" }, { "vistas", 650 }, { "estado", "disponible" }, { "totalComentarios", 4 }, { "totalLikes", 19 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-18)) } },
                new() { { "titulo", "Mate autocebante impreso" }, { "descripcion", "Mate térmico con bombilla de acero inoxidable incluida. Diseño ergonómico, capacidad 250ml." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post07/400/300" } }, { "precio", 2800.0 }, { "webLink", null }, { "autor", "seed_user_3" }, { "vistas", 1800 }, { "estado", "disponible" }, { "totalComentarios", 8 }, { "totalLikes", 44 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-15)) } },
                new() { { "titulo", "Cortador de galletas navideñas" }, { "descripcion", "Pack de 6 moldes navideños (árbol, estrella, muñeco, campana, bastón, copo) aptos para uso gastronómico." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post08/400/300", "https://picsum.photos/seed/post08b/400/300", "https://picsum.photos/seed/post08c/400/300", "https://picsum.photos/seed/post08d/400/300", "https://picsum.photos/seed/post08e/400/300", "https://picsum.photos/seed/post08f/400/300" } }, { "precio", 800.0 }, { "webLink", null }, { "autor", "seed_user_4" }, { "vistas", 120 }, { "estado", "disponible" }, { "totalComentarios", 2 }, { "totalLikes", 3 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-12)) } },
                new() { { "titulo", "Soporte celular de mesa" }, { "descripcion", "Soporte universal regulable en inclinación para smartphones y tablets hasta 12 pulgadas." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post09/400/300" } }, { "precio", 1000.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 980 }, { "estado", "disponible" }, { "totalComentarios", 1 }, { "totalLikes", 11 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-10)) } },
                new() { { "titulo", "Lámpara de noche Luna 3D" }, { "descripcion", "Lámpara con textura realista de la luna y luz LED multicolor de bajo consumo. Incluye control remoto." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post10/400/300", "https://picsum.photos/seed/post10b/400/300" } }, { "precio", 8500.0 }, { "webLink", "https://example.com/lampara-luna" }, { "autor", "seed_user_2" }, { "vistas", 3200 }, { "estado", "disponible" }, { "totalComentarios", 11 }, { "totalLikes", 89 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-8)) } },
                new() { { "titulo", "Caja organizadora con tapa" }, { "descripcion", "Caja hexagonal modular para organización de escritorio. Apilable, tapa a presión." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post11/400/300" } }, { "precio", 1200.0 }, { "webLink", null }, { "autor", "seed_user_5" }, { "vistas", 430 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 7 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-7)) } },
                new() { { "titulo", "Repositorio de cuchillos magnético" }, { "descripcion", "Barra magnética impresa con imanes de neodimio incrustados para cuchillos de cocina." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post12/400/300" } }, { "precio", 2200.0 }, { "webLink", null }, { "autor", "seed_user_3" }, { "vistas", 670 }, { "estado", "disponible" }, { "totalComentarios", 2 }, { "totalLikes", 15 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-6)) } },
                new() { { "titulo", "Máscara de Iron Man" }, { "descripcion", "Máscara réplica de Iron Man Mark III. Calza adulto, pintada a mano con detalles LED." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post13/400/300", "https://picsum.photos/seed/post13b/400/300" } }, { "precio", 9500.0 }, { "webLink", null }, { "autor", "seed_user_4" }, { "vistas", 5600 }, { "estado", "disponible" }, { "totalComentarios", 22 }, { "totalLikes", 178 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-5)) } },
                new() { { "titulo", "Juego de ajedrez temático" }, { "descripcion", "Juego de ajedrez completo con piezas temáticas medievales. Tablero plegable incluido." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post14/400/300" } }, { "precio", 6500.0 }, { "webLink", null }, { "autor", "seed_user_5" }, { "vistas", 890 }, { "estado", "disponible" }, { "totalComentarios", 6 }, { "totalLikes", 31 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-4)) } },
                new() { { "titulo", "Portalápices Rocket" }, { "descripcion", "Portalápices con forma de cohete espacial. 15cm de alto, base estable." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post15/400/300" } }, { "precio", 900.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 245 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 5 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-3)) } },
                new() { { "titulo", "Estuche para lápices" }, { "descripcion", "Estuche con cierre cremallera personalizable. Varios colores disponibles bajo pedido." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post16/400/300" } }, { "precio", 1800.0 }, { "webLink", null }, { "autor", "seed_user_2" }, { "vistas", 510 }, { "estado", "disponible" }, { "totalComentarios", 1 }, { "totalLikes", 9 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-2)) } },
                new() { { "titulo", "Carcasa para Raspberry Pi" }, { "descripcion", "Carcasa con ventilación optimizada para Raspberry Pi 4/5. Incluye soporte para disipador." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post17/400/300" } }, { "precio", 1300.0 }, { "webLink", "https://example.com/carcasa-rpi" }, { "autor", "seed_user_3" }, { "vistas", 780 }, { "estado", "disponible" }, { "totalComentarios", 3 }, { "totalLikes", 22 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-1)) } },
                new() { { "titulo", "Posavasos geek" }, { "descripcion", "Set de 4 posavasos con diseños de videojuegos clásicos. Diámetro 9cm." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post18/400/300" } }, { "precio", 600.0 }, { "webLink", null }, { "autor", "seed_user_4" }, { "vistas", 195 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 2 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Soporte para cepillos de dientes" }, { "descripcion", "Organizador de baño con capacidad para 4 cepillos y tubo de pasta dental." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post19/400/300" } }, { "precio", 750.0 }, { "webLink", null }, { "autor", "seed_user_5" }, { "vistas", 320 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 6 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Llavero con código QR" }, { "descripcion", "Llavero personalizable con código QR grabado. Ideal para negocios y redes sociales." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post20/400/300" } }, { "precio", 350.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 1100 }, { "estado", "disponible" }, { "totalComentarios", 4 }, { "totalLikes", 18 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Cable organizer magnético" }, { "descripcion", "Clip magnético para organizar cables de escritorio. Pack de 3 unidades." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post21/400/300" } }, { "precio", 450.0 }, { "webLink", null }, { "autor", "seed_user_2" }, { "vistas", 540 }, { "estado", "disponible" }, { "totalComentarios", 1 }, { "totalLikes", 10 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Mini jardinero colgante" }, { "descripcion", "Maceta colgante con sistema de autorriego. Ideal para suculentas y cactus." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post22/400/300" } }, { "precio", 1100.0 }, { "webLink", null }, { "autor", "seed_user_3" }, { "vistas", 410 }, { "estado", "reservado" }, { "totalComentarios", 2 }, { "totalLikes", 14 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Anillo ajustable impreso" }, { "descripcion", "Anillo de diseño geométrico ajustable. Material PLA biocompatible." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post23/400/300" } }, { "precio", 250.0 }, { "webLink", null }, { "autor", "seed_user_4" }, { "vistas", 870 }, { "estado", "vendido" }, { "totalComentarios", 0 }, { "totalLikes", 8 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Base giratoria para exposición" }, { "descripcion", "Base giratoria motorizada para exhibir piezas 3D. Velocidad ajustable, alimentación USB." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post24/400/300" } }, { "precio", 4500.0 }, { "webLink", "https://example.com/base-giratoria" }, { "autor", "seed_user_5" }, { "vistas", 1500 }, { "estado", "disponible" }, { "totalComentarios", 7 }, { "totalLikes", 35 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } },
                new() { { "titulo", "Portalápices minimalista" }, { "descripcion", "Portalápices de escritorio con diseño minimalista. Capacidad para 15 lápices." }, { "imagenes", new List<string> { "https://picsum.photos/seed/post25/400/300" } }, { "precio", 700.0 }, { "webLink", null }, { "autor", "seed_user_1" }, { "vistas", 280 }, { "estado", "disponible" }, { "totalComentarios", 0 }, { "totalLikes", 3 }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow) } }
            };

            var seedUsers = new Dictionary<string, Dictionary<string, object>>
            {
                ["seed_user_1"] = new() { { "profileName", "Carlos López" }, { "username", "carlos3d" }, { "email", "carlos@ejemplo.com" }, { "profilePicture", "https://picsum.photos/seed/user1/200/200" }, { "presentation", "Diseñador 3D freelance. Especialista en piezas funcionales." }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-60)) } },
                ["seed_user_2"] = new() { { "profileName", "María García" }, { "username", "mariastudio" }, { "email", "maria@ejemplo.com" }, { "profilePicture", "https://picsum.photos/seed/user2/200/200" }, { "presentation", "Artista digital y modeladora 3D. Figuras coleccionables." }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-55)) } },
                ["seed_user_3"] = new() { { "profileName", "Juan Martínez" }, { "username", "juanmaqueta" }, { "email", "juan@ejemplo.com" }, { "profilePicture", "https://picsum.photos/seed/user3/200/200" }, { "presentation", "Creador de maquetas arquitectónicas impresas en 3D." }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-50)) } },
                ["seed_user_4"] = new() { { "profileName", "Ana Rodríguez" }, { "username", "anageek" }, { "email", "ana@ejemplo.com" }, { "profilePicture", "https://picsum.photos/seed/user4/200/200" }, { "presentation", "Cosplayer y creadora de accesorios impresos en 3D." }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-45)) } },
                ["seed_user_5"] = new() { { "profileName", "Pedro Sánchez" }, { "username", "pedroprints" }, { "email", "pedro@ejemplo.com" }, { "profilePicture", "https://picsum.photos/seed/user5/200/200" }, { "presentation", "Ingeniero y maker. Creo soluciones prácticas para el hogar." }, { "createdAt", Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-40)) } }
            };

            foreach (var kvp in seedUsers)
            {
                var existing = await _firestoreDb.Collection("users").Document(kvp.Key).GetSnapshotAsync();
                if (!existing.Exists)
                    await _firestoreDb.Collection("users").Document(kvp.Key).SetAsync(kvp.Value);
            }

            foreach (var post in seedPosts)
            {
                await _firestoreDb.Collection("posts").AddAsync(post);
            }

            Console.WriteLine("✅ Datos de prueba sembrados: 25 posts, 5 usuarios.");
        }
    }
}
